### ISSUE TITLE
Flag for including/excluding a package from deployment?

### ISSUE THREAD

**Issue by RobIsHere** [94726/action-turborepo-changes#36]
Thanks for this gh-action! I've seen that you are already checking the "private": true/false flag in package.json. The problem with private flag is that it already has the meaning "refuse to publish to npm" officially. Therefore I need that flag at false also in packages that should be deployed via GH Actions.

It would be great to also have a dedicated "deploy-changes" or "deploy": true/false flag checked. If the "deploy" exists in package.json it should exclude on false and include on true.

**Comment by 94726** [comment]
I see why you would want that, but `deploy` [doesn't seem to be common key of package.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-json) and I'm not really comfortable with creating custom keys specific to this action.

Instead you could also create a separate pipeline `deploy`, that only exists in packages that need it.


But generally I agree, there should probably be a more flexible way of configuring such unique cases. I'm thinking about adding a flag that makes `outputs.packages` include the whole package.json of that package. That way you could do more complex filtering yourself.

Another idea is to have something like this:
```yaml

- name: Collect Turborepo Changes
  id: turborepoChanges
  uses: 94726/action-turborepo-changed@v1
  env:
    PACKAGE_JSON_FILTER: |
      - deploy: true
```
where `PACKAGE_JSON_FILTER` represents the first level of the package.json and is used to compare against it.
